/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package windowsApp;

import SwingTools.SwingTools;
import exceptions.ExceptionsDao;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author dafna
 */
public class Informations extends javax.swing.JInternalFrame {

    /**
     * Creates new form Informations
     *
     * @param type
     */
    public Informations(String type) {
        initComponents();
        if (type.equalsIgnoreCase("galaxy")) {
            try {
                SwingTools.getSwingTools().generateSelect(galaxy, "galaxy");
            } catch (SQLException | ExceptionsDao ex) {
                JOptionPane.showMessageDialog(this, "" + ex.getMessage(), "Message", JOptionPane.WARNING_MESSAGE);
            }
        } else {
            galaxy.setVisible(false);
            search.setVisible(false);
            if (type.equalsIgnoreCase("spaceships")) {
                AllSpaceships spaceshipsInfo = new AllSpaceships();
                scrollPanel.setViewportView(spaceshipsInfo);
            } else {
                SpaceportsStatus spaceports = new SpaceportsStatus();
                scrollPanel.setViewportView(spaceports);
            }
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        galaxy = new javax.swing.JComboBox<>();
        search = new javax.swing.JButton();
        scrollPanel = new javax.swing.JScrollPane();

        search.setText("Search ...");
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });

        scrollPanel.setBorder(null);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(galaxy, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 94, Short.MAX_VALUE)
                .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74))
            .addComponent(scrollPanel)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(galaxy, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(scrollPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 383, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Method that call Dao for show informations about spaceports by certain
     * galaxy
     *
     * @param evt
     */
    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        String galaxyName = galaxy.getSelectedItem().toString();
        if (galaxyName.equalsIgnoreCase("Choose a galaxy")) {
            JOptionPane.showMessageDialog(this, "You have not selected any galaxy", "Message", JOptionPane.WARNING_MESSAGE);
        } else {
            SpaceportsInformationByGalaxy spaceportInfo = new SpaceportsInformationByGalaxy(galaxyName);
            scrollPanel.setViewportView(spaceportInfo);
        }
    }//GEN-LAST:event_searchActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> galaxy;
    private javax.swing.JScrollPane scrollPanel;
    private javax.swing.JButton search;
    // End of variables declaration//GEN-END:variables
}
