/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package windowsApp;

import SwingTools.SwingTools;
import exceptions.ExceptionsDao;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author dafna
 */
public class Informations extends javax.swing.JInternalFrame {

    /**
     * Creates new form Informations
     *
     * @param type
     */
    public Informations(String type) {
        initComponents();
        if (type.equalsIgnoreCase("galaxy")) {
            try {
                SwingTools.getSwingTools().generateSelect(galaxy, "galaxy");
            } catch (SQLException | ExceptionsDao ex) {
                JOptionPane.showMessageDialog(this, "" + ex.getMessage(), "Message", JOptionPane.WARNING_MESSAGE);
            }           
        } else {
            galaxy.setVisible(false);
            search.setVisible(false);
            if(type.equalsIgnoreCase("spaceships")){
                AllSpaceships spaceshipsInfo = new AllSpaceships(); 
                scrollPanel.setViewportView(spaceshipsInfo); 
            }
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        galaxy = new javax.swing.JComboBox<>();
        search = new javax.swing.JButton();
        scrollPanel = new javax.swing.JScrollPane();

        search.setText("Search ...");
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });

        scrollPanel.setBorder(null);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(galaxy, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(230, Short.MAX_VALUE))
            .addComponent(scrollPanel)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(search, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                    .addComponent(galaxy))
                .addGap(18, 18, 18)
                .addComponent(scrollPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 379, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        String galaxyName = galaxy.getSelectedItem().toString();
        if(galaxyName.equalsIgnoreCase("Choose a galaxy")){
            JOptionPane.showMessageDialog(this, "You have not selected any galaxy", "Message", JOptionPane.WARNING_MESSAGE);
        }else{
            SpaceportsInformationByGalaxy spaceportInfo = new SpaceportsInformationByGalaxy(galaxyName);            
            scrollPanel.setViewportView(spaceportInfo);            
        }
    }//GEN-LAST:event_searchActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> galaxy;
    private javax.swing.JScrollPane scrollPanel;
    private javax.swing.JButton search;
    // End of variables declaration//GEN-END:variables
}
