/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package windowsApp;

import Exceptions.ExceptionsDatabase;
import SwingTools.SwingTools;
import dao.Dao;
import exceptions.ExceptionsDao;
import exceptions.InputException;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import models.Runway;
import models.Spaceport;
import models.Spaceship;

/**
 *
 * @author yuli
 */
public class LandingSpaceship extends javax.swing.JDialog {

    List<Spaceport> spaceportsApp = new ArrayList<>();
    List<Runway> runwaysApp = new ArrayList<>();

    /**
     * Creates new form LandingSpaceship
     *
     * @param parent
     * @param modal
     * @throws exceptions.InputException
     */
    public LandingSpaceship(java.awt.Frame parent, boolean modal) throws InputException {
        super(parent, modal);
        initComponents();
        try {
            SwingTools.getSwingTools().generateSelect(spaceship, "landing");
            SwingTools.getSwingTools().generateSelect(spaceport, "spaceport");
        } catch (SQLException | ExceptionsDao ex) {
            JOptionPane.showMessageDialog(this, "" + ex.getMessage(), "Message", JOptionPane.WARNING_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        spaceship = new javax.swing.JComboBox<>();
        spaceport = new javax.swing.JComboBox<>();
        runway = new javax.swing.JComboBox<>();
        landed = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Landing");

        spaceport.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                spaceportItemStateChanged(evt);
            }
        });

        landed.setText("Landing spaceship");
        landed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                landedActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(spaceship, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(spaceport, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(runway, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(194, 194, 194)
                        .addComponent(landed, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(runway, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                    .addComponent(spaceport)
                    .addComponent(spaceship))
                .addGap(56, 56, 56)
                .addComponent(landed, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(65, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Generate dynamic combobox
     *
     * @param evt
     */
    private void spaceportItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_spaceportItemStateChanged
        String spaceportSelected = spaceport.getSelectedItem().toString();
        if (spaceportSelected.equalsIgnoreCase("Choose a runway")) {
            JOptionPane.showMessageDialog(this, "You have not selected any runway", "Message", JOptionPane.WARNING_MESSAGE);
        } else {
            try {
                SwingTools.getSwingTools().generateDynamicSelect(runway, spaceportSelected, "FREE");
            } catch (SQLException | ExceptionsDao ex) {
                JOptionPane.showMessageDialog(this, "" + ex.getMessage(), "Message", JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_spaceportItemStateChanged

    /**
     * Method that call Dao for update data of spaceship in case of landing
     *
     * @param evt
     */
    private void landedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_landedActionPerformed
        String spaceportSelected = spaceport.getSelectedItem().toString();
        String spaceshipSelected = spaceship.getSelectedItem().toString();
        String runwaySelected = runway.getSelectedItem().toString();
        try {
            Spaceship spaceshipChecked = Dao.getDao().getSpaceshipByName(spaceshipSelected);
            Dao.getDao().updateSpaceshipRunwayLanding(spaceshipChecked, runwaySelected, spaceportSelected);
            JOptionPane.showMessageDialog(this, "Spaceship landed successful", "Message", JOptionPane.INFORMATION_MESSAGE);
            SwingTools.getSwingTools().generateSelect(spaceship, "landing");
            spaceport.setSelectedIndex(0);
            runway.setSelectedIndex(0);
        } catch (SQLException | ExceptionsDatabase | ExceptionsDao ex) {
            JOptionPane.showMessageDialog(this, "" + ex.getMessage(), "Message", JOptionPane.WARNING_MESSAGE);
        }


    }//GEN-LAST:event_landedActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton landed;
    private javax.swing.JComboBox<String> runway;
    private javax.swing.JComboBox<String> spaceport;
    private javax.swing.JComboBox<String> spaceship;
    // End of variables declaration//GEN-END:variables
}
