/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package windowsApp;

/**
 *
 * @author dafna
 */
public class MainInterface extends javax.swing.JFrame {

    /**
     * Creates new form MainInterface
     */
    public MainInterface() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JMenuBar();
        general = new javax.swing.JMenu();
        newSpaceport = new javax.swing.JMenuItem();
        newRunway = new javax.swing.JMenuItem();
        newSpaceship = new javax.swing.JMenuItem();
        deleteSpaceship = new javax.swing.JMenuItem();
        flight = new javax.swing.JMenu();
        landings = new javax.swing.JMenuItem();
        departures = new javax.swing.JMenuItem();
        notifications = new javax.swing.JMenu();
        endCleaning = new javax.swing.JMenuItem();
        endMaintenance = new javax.swing.JMenuItem();
        informations = new javax.swing.JMenu();
        spaceships = new javax.swing.JMenuItem();
        spaceports = new javax.swing.JMenuItem();
        spaceportsStatus = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        general.setText("General");

        newSpaceport.setText("New spaceport");
        newSpaceport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newSpaceportActionPerformed(evt);
            }
        });
        general.add(newSpaceport);

        newRunway.setText("New runway");
        general.add(newRunway);

        newSpaceship.setText("New spaceship");
        general.add(newSpaceship);

        deleteSpaceship.setText("Delete spaceship");
        general.add(deleteSpaceship);

        mainPanel.add(general);

        flight.setText("Flight");

        landings.setText("Landings");
        flight.add(landings);

        departures.setText("Departures");
        flight.add(departures);

        mainPanel.add(flight);

        notifications.setText("Notifications");

        endCleaning.setText("End of cleaning");
        notifications.add(endCleaning);

        endMaintenance.setText("End of maintenance");
        notifications.add(endMaintenance);

        mainPanel.add(notifications);

        informations.setText("Informations");

        spaceships.setText("Spaceships");
        informations.add(spaceships);

        spaceports.setText("Spaceports");
        informations.add(spaceports);

        spaceportsStatus.setText("Spaceports Status");
        informations.add(spaceportsStatus);

        mainPanel.add(informations);

        setJMenuBar(mainPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 716, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 418, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
/**
     * Open a window to create a new spaceport
     *
     * @param evt
     */
    private void newSpaceportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newSpaceportActionPerformed
        NewSpaceport newSpaceport = new NewSpaceport(this, true);
        newSpaceport.setLocationRelativeTo(null);
        newSpaceport.setVisible(true);
    }//GEN-LAST:event_newSpaceportActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainInterface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem deleteSpaceship;
    private javax.swing.JMenuItem departures;
    private javax.swing.JMenuItem endCleaning;
    private javax.swing.JMenuItem endMaintenance;
    private javax.swing.JMenu flight;
    private javax.swing.JMenu general;
    private javax.swing.JMenu informations;
    private javax.swing.JMenuItem landings;
    private javax.swing.JMenuBar mainPanel;
    private javax.swing.JMenuItem newRunway;
    private javax.swing.JMenuItem newSpaceport;
    private javax.swing.JMenuItem newSpaceship;
    private javax.swing.JMenu notifications;
    private javax.swing.JMenuItem spaceports;
    private javax.swing.JMenuItem spaceportsStatus;
    private javax.swing.JMenuItem spaceships;
    // End of variables declaration//GEN-END:variables
}
