/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package windowsApp;

import SwingTools.SwingTools;
import dao.Dao;
import exceptions.ExceptionsDao;
import exceptions.InputException;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import models.Runway;
import tools.ToolsApp;

/**
 *
 * @author dafna
 */
public class NewRunway extends javax.swing.JDialog {

    /**
     * Creates new form NewRunway
     */
    public NewRunway(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        nameRequired.setVisible(false);
        spaceportRequired.setVisible(false);
        try {
            SwingTools.getSwingTools().generateSelect(spaceport, "spaceport");
        } catch (SQLException | ExceptionsDao ex) {
            JOptionPane.showMessageDialog(this, "" + ex.getMessage(), "Message", JOptionPane.WARNING_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nameRunway = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        nameRequired = new javax.swing.JLabel();
        addRunway = new javax.swing.JButton();
        spaceport = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        spaceportRequired = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("New Runway");

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Name of runway");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Select a spaceport");

        nameRunway.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                nameRunwayFocusLost(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setText("*");

        nameRequired.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        nameRequired.setForeground(new java.awt.Color(255, 0, 0));
        nameRequired.setText("Name is required");

        addRunway.setText("Add a new runway");
        addRunway.setToolTipText("");
        addRunway.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addRunwayActionPerformed(evt);
            }
        });

        spaceport.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                spaceportFocusLost(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 0, 0));
        jLabel5.setText("*");

        spaceportRequired.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        spaceportRequired.setForeground(new java.awt.Color(255, 0, 0));
        spaceportRequired.setText("Spaceport is required");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(spaceportRequired, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(nameRequired, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nameRunway)
                                    .addComponent(spaceport, 0, 261, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(72, 72, 72))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(addRunway, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(166, 166, 166))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                        .addComponent(jLabel3))
                    .addComponent(nameRunway, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nameRequired)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(spaceport, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(spaceportRequired)
                .addGap(65, 65, 65)
                .addComponent(addRunway, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(87, Short.MAX_VALUE))
        );

        getAccessibleContext().setAccessibleName("New Runway");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Check data of input "spaceport"
     *
     * @param evt
     */
    private void spaceportFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_spaceportFocusLost
        checkSelect();
    }//GEN-LAST:event_spaceportFocusLost

    private void nameRunwayFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nameRunwayFocusLost
        String runway = nameRunway.getText();
        if (runway.equalsIgnoreCase("") || runway.trim().equalsIgnoreCase("")) {
            nameRequired.setVisible(true);
        } else {
            nameRequired.setVisible(false);
        }
    }//GEN-LAST:event_nameRunwayFocusLost

    /**
     * Method that call Dao to insert new runway in database
     *
     * @param evt
     */
    private void addRunwayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addRunwayActionPerformed
        String spaceportSelected = checkSelect();
        if (spaceportSelected == null) {
            spaceportRequired.setVisible(true);
        } else {
            try {
                int runway = ToolsApp.convertStringToNumber(nameRunway.getText());
                Runway newRunway = new Runway(runway);
                if (Dao.getDao().existRunway(newRunway, spaceportSelected)) {
                    JOptionPane.showMessageDialog(this, "Runway already exist", "Message", JOptionPane.WARNING_MESSAGE);
                } else {
                    Dao.getDao().insertRunway(newRunway, spaceportSelected);
                    JOptionPane.showMessageDialog(this, "Runway created successful", "Message", JOptionPane.INFORMATION_MESSAGE);
                    nameRunway.setText("");
                    spaceport.setSelectedIndex(0);
                }
            } catch (InputException ex) {
                JOptionPane.showMessageDialog(this, "" + ex.getMessage(), "Message", JOptionPane.WARNING_MESSAGE);
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, "" + ex.getMessage(), "Message", JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_addRunwayActionPerformed

    /**
     * Check if spaceport has been selected
     *
     * @return
     */
    private String checkSelect() {
        String spaceportSelected = spaceport.getSelectedItem().toString();
        int selectedIndexSpaceport = spaceport.getSelectedIndex();
        if (spaceportSelected.equalsIgnoreCase("Choose a spaceport") || selectedIndexSpaceport == -1) {
            spaceportRequired.setVisible(true);
        } else {
            spaceportRequired.setVisible(false);
            return spaceportSelected;
        }
        return null;
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addRunway;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel nameRequired;
    private javax.swing.JTextField nameRunway;
    private javax.swing.JComboBox<String> spaceport;
    private javax.swing.JLabel spaceportRequired;
    // End of variables declaration//GEN-END:variables
}
